### ISSUE TITLE
Not working with Froala editor in chrome browser

### ISSUE THREAD

**Issue by daptontech** [wiris/mathtype-integration-js-dev#29]
**Expected behavior.**
Maths equation should display using `froalaView`

**Actual behavior.**
Maths equation are not getting displayed only numbers are displayed (works as expected in Firefox).

**Steps to reproduce the problem.**
Follow the steps mentioned in https://github.com/wiris/mathtype-integration-js-dev/blob/stable/doc/frameworks/AngularJS/froala/froala-2_9_5.md

Created a simple form

```
import {Component} from '@angular/core';
import {FormControl, FormGroup} from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'my-app';
  profileForm = new FormGroup({
    formModel: new FormControl(''),
  });
  public options: any = {
    toolbarButtons: ['undo', 'redo', 'bold', 'wirisEditor', 'wirisChemistry']
  };

  onSubmit() {
  }
}
```

```
<form [formGroup]="profileForm" (ngSubmit)="onSubmit()">
  <textarea [froalaEditor]="options" formControlName="formModel" [(froalaModel)]="profileForm.formModel"></textarea>
  <div [froalaView]="profileForm.formModel"></div>
  <button type="submit">Submit</button>
</form>
```

**OS.**
macOS 10.14.6

**Browser.**
Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by carla-at-wiris** [comment]
**Why this happens?** 

   Because Chrome does not render automatically MathML formulas, but firefox does.

**How to solve it?**

   You will have to create some functions and use a wiris library to render the formulas manualy and correctly. The function is com.wiris.js.JsPluginViewer.parseElement(htmlcontent)

   Your html should have different and new elements. Following your html example, now it should look like:

```
<form [formGroup]="profileForm" (ngSubmit)="onSubmit()">
  <textarea [froalaEditor]="options" formControlName="formModel" [(froalaModel)]="profileForm.formModel" (froalaModelChange)="onChangeContent()"></textarea>
  <div id="contentDiv"></div>
  <button type="submit">Submit</button>
</form>
```
We changed the div tag and added a function to the textarea tag. This function will be called every time the Froala editor content is changed, and will update the div content with the Froala content correctly renderized.

To have this wiris functionality that renders the formulas to see them as expected, you'll have to add the following script on your project:

`https://www.wiris.net/demo/plugins/app/WIRISplugins.js?viewer=image`
You'll also have to add the following lines inside the app component class to have the behavior mentioned in the previous line:

```
  onChangeContent() {
    const editorContent = (window as any).FroalaEditor.INSTANCES[0].html.get();
    document.getElementById("contentDiv")[removed] = editorContent;
    (window as any).com.wiris.js.JsPluginViewer.parseElement(document.getElementById("contentDiv"));    
  }
```
and inside the options object that defines the Froala behavior, you'll have to add the beginning behavior of the content div:

```
public options: any = {
    ...
    events: {
      initialized() {
      
        // Set initial behavior
        const editorContent = (window as any).FroalaEditor.INSTANCES[0].html.get();
        if (editorContent == "") {
          document.getElementById("contentDiv")[removed] = "undefined";
        } else (window as any).com.wiris.js.JsPluginViewer.parseElement(document.getElementById("contentDiv"));
      },
    },
  };
```
With this changes you'll be able to see the behavior expected on the formulas. Remember that this is necessary because chrome browser does not do it by itself, so we have to make it.
